return {
	{ "<F2>", desc = "Rename" },
	{ "<leader>rn", desc = "Rename" },
	{
		"<leader>fr",
		'<cmd>lua require("telescope").extensions.refactoring.refactors()<CR>',
		mode = { "n", "x" },
		desc = "Refactors",
	},
	{
		"<leader>ri",
		'<cmd>lua require("refactoring").refactor("Inline Variable")<CR>',
		mode = { "n", "x" },
		desc = "Inline variable",
		expr = true,
	},
	{
		"<leader>rb",
		'<cmd>lua require("refactoring").refactor("Extract Block")<CR>',
		mode = { "n", "x" },
		desc = "Extract block",
		expr = true,
	},
	{
		"<leader>rf",
		'<cmd>lua require("refactoring").refactor("Extract Block To File")<CR>',
		mode = { "n", "x" },
		desc = "Extract block to file",
		expr = true,
	},
	{
		"<leader>rP",
		'<cmd>lua require("refactoring").debug.printf({ below = false })<CR>',
		desc = "Debug print",
	},
	{
		"<leader>rp",
		'<cmd>lua require("refactoring").debug.print_var({ normal = true })<CR>',
		mode = { "n", "x" },
		desc = "Debug print variable",
	},
	{
		"<leader>rc",
		'<cmd>lua require("refactoring").debug.cleanup({})<CR>',
		desc = "Debug cleanup",
	},
	{
		"<leader>rf",
		'<cmd>lua require("refactoring").refactor("Extract Function")<CR>',
		mode = { "n", "x" },
		desc = "Extract function",
		expr = true,
	},
	{
		"<leader>rF",
		'<cmd>lua require("refactoring").refactor("Extract Function To File")<CR>',
		mode = { "n", "x" },
		desc = "Extract function to file",
		expr = true,
	},
	{
		"<leader>rx",
		'<cmd>lua require("refactoring").refactor("Extract Variable")<CR>',
		mode = { "n", "x" },
		desc = "Extract variable",
		expr = true,
	},
	{
		"<leader>rp",
		'<cmd>lua require("refactoring").debug.print_var()<CR>',
		mode = { "n", "x" },
		desc = "Debug print variable",
	},
}
