return {
	{ "[",             group = "Prev" },
	{ "]",             group = "Next" },
	{ "g",             group = "Goto" },
	{ "gs",            group = "Surround" },
	{ "z",             group = "Fold" },
	{ "s",             group = "Quick substitute" },
	{ "<leader>a",     group = "AI",                     mode = { "n", "x" } },
	{ "<leader>b",     group = "Buffer" },
	{ "<leader>c",     group = "Codes" },
	{ "<leader>cm",    group = "Code map" },
	{ "<leader>D",     group = "Database" },
	{ "<leader>e",     group = "File picker" },
	{ "<leader>f",     group = "Telescope extension",    mode = { "n", "x" } },
	{ "<leader>g",     group = "Git" },
	{ "<leader>gh",    group = "Github" },
	{ "<leader>ghi",   group = "Issues" },
	{ "<leader>ghc",   group = "Commits" },
	{ "<leader>ghl",   group = "Litee" },
	{ "<leader>ghp",   group = "Pull Request" },
	{ "<leader>ghr",   group = "Review" },
	{ "<leader>ght",   group = "Threads" },
	{ "<leader>h",     group = "Hunks" },
	{ "<leader>m",     group = "Metals" },
	{ "<leader>p",     group = "Pin" },
	{ "<leader>P",     group = "Projects" },
	{ "<leader>R",     group = "Rest API (only ft=http)" },
	{ "<leader>s",     group = "Search & Replace",       mode = { "n", "x" } },
	{ "<leader>S",     group = "Session" },
	{ "<leader>u",     group = "Ui settings" },
	{ "<leader>x",     group = "Diagnostics" },
	{ "<leader>y",     group = "Launchers" },
	{ "<leader><tab>", group = "Tab" },
	{ "<leader>w",     group = "Window" },
}
